spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_zero_code_hub
    username: root
    password: ${DATABASE_PASSWORD}
  application:
   name: ai-zero-code-hub

server:
  port: 8123
  servlet:
    context-path: /api


springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.swu.aiZeroCodeHub


knife4j:
  enable: true
  setting:
    language: zh_cn
